Fixes an issue where asking a mock for values in a concurrent way causes a crash in the VerifyContainer
MetalheadSanya/swift-mock pull request #69
Opened 2024-11-22 19:39 UTC by kevmalek

2024-11-22 19:46 UTC, NineToeNerd approved these changes

2024-12-05 18:54 UTC, NineToeNerd requested changes
We need the same fix in the `InOrderContainer`

2025-01-08 11:22 UTC, MetalheadSanya requested changes

2025-01-08 11:22 UTC, MetalheadSanya commented on Sources/SwiftMock/Verify/VerifyContainer.swift
> +        queue.sync { [weak self] in
Kinda wierd. We call closure synchronous on the queue, but capture self in a weak manner. 
Just use unowned reference

2025-01-08 11:22 UTC, MetalheadSanya commented on Sources/SwiftMock/Verify/VerifyContainer.swift
> +    private let queue = DispatchQueue(label: "VerifyContainerQueue")
fix indentation, please

2026-04-20 21:33 UTC, closed without merging